cc_binary(
    name = "test_hirm_animals",
    srcs = ["test_hirm_animals.cc"],
    deps = [
        "//:headers",
        "//:util_distribution_variant",
        "//:util_io",
        "//distributions",
    ],
)

cc_binary(
    name = "test_irm_two_relations",
    srcs = ["test_irm_two_relations.cc"],
    deps = [
        "//:headers",
        "//:irm",
        "//:util_distribution_variant",
        "//:util_io",
        "//distributions",
    ],
)

cc_binary(
    name = "test_misc",
    srcs = ["test_misc.cc"],
    deps = [
        "//:headers",
        "//:util_distribution_variant",
        "//:util_io",
        "//distributions",
    ],
)
